### ISSUE TITLE
Extract neverNullable

### ISSUE THREAD

**Issue by jsonberry** [marblejs/example#28]
Hey @JozefFlakus I am loving the Marble project - I haven't even had a chance to try it out yet, but I read a blog post and have looked at the project + examples and really excited to play around with it.

I liked the neverNullable operator you made here: https://github.com/marblejs/example/blob/master/src/util/rxjs.util.ts

I just started the [rxjs-toolkit](https://github.com/jsonberry/rxjs-toolkit) project, which will be a collection of custom operators. There's an idea floating around that the `rxjs` community will have a "marketplace" of custom operators to choose from, something we can add to the new docs, and before that idea morphs into something that more people are contributing to, I wanted to start the collection now and have `rxjs-toolkit` be the starting place for the collection.

I want to extract `neverNullable` and add it to `rxjs-toolkit`. This github issue isn't a feature request to use neverNullable from `rxjs-toolkit`, it's more of just a way to get a message out to you about how I'd like to add it and see if you were OK with that. At the very least, I plan on adding it and contributing it to your work here.

After I add it if you have time to get :eyes: on the port to see if any mistakes were made that would be much apprecated! 😄

Closing this issue immediately because I just wanted to get this message out to ya. 👋 
[@jsonberry on Twitter](https://twitter.com/jsonberrry)

**Comment by JozefFlakus** [comment]
Hi @jsonberry!

Sure, no problem. It's just a small function with a fancy naming. ☺️
Big thanks for all kind words!

PS. When you will have some time to play around with Marble, please give us some impressions. The end feedback is very important for future releases! 💪
