### ISSUE TITLE
(yarn docker) doesn't exists

### ISSUE THREAD

**Issue by zeucxb** [marblejs/example#9]
The command `yarn docker` documented in the project `README` file, doesn't exists.

It had been removed, or it'll be add?

**Comment by JozefFlakus** [comment]
It will be added. I forgot that the dockerized mongodb is on the different branch...

**Comment by zeucxb** [comment]
I add `"docker": "cd .docker && docker-compose up"` here.

**Comment by JozefFlakus** [comment]
Please don't - it is still not pushed to `master` branch.

**Comment by zeucxb** [comment]
I mean. I did in my personal project.
